- Command/BaseBootstrapSymlinkCommand.php
- Command/InstallFontCommand.php
- Composer/ScriptHandler.php
- DependencyInjection/Configuration.php
- Form/Extension/IconButtonExtension.php
- Resources/meta/LICENSE
|Q            |A  |
|---          |---|
|Bug Fix?     |n  |
|New Feature? |n  |
|BC Breaks?   |n  |
|Deprecations?|n  |
|Tests Pass?  |n  |
|Fixed Tickets|   |
|License      |MIT|
|Doc PR       |   |
Sent using [Gush](https://github.com/gushphp/gush)
> minor improvements

- Resources/doc/3-form-extension-templates.md
Added missing `render_optional_text` option and corrected default for `render_required_asterisk`
> Fixed form configuration

- Resources/public/sass/mopabootstrapbundle-3.2.scss
same as https://github.com/phiamo/MopaBootstrapBundle/pull/1018
(angry)
> make $icon-font-path able to override

- Resources/public/js/mopabootstrap-collection.js
> Fix broken nested collections with custom prototype names

- Command/BaseBootstrapSymlinkCommand.php
- Command/InstallFontCommand.php
- DependencyInjection/MopaBootstrapExtension.php
- Form/Extension/DateTypeExtension.php
- Form/Extension/DatetimeTypeExtension.php
- Form/Extension/ErrorTypeFormTypeExtension.php
- Form/Extension/HelpFormTypeExtension.php
- Form/Extension/HorizontalFormTypeExtension.php
- Form/Extension/IconButtonExtension.php
- Form/Extension/LegendFormTypeExtension.php
- Form/Extension/OffsetButtonExtension.php
- Form/Extension/StaticTextExtension.php
- Form/Extension/TabbedFormTypeExtension.php
- Form/Extension/TimeTypeExtension.php
- Form/Extension/WidgetCollectionFormTypeExtension.php
- Form/Extension/WidgetFormTypeExtension.php
- Menu/Converter/MenuConverter.php
- MopaBootstrapBundle.php
- Resources/public/sass/initializr_addons.scss
- Tests/Form/AbstractDivLayoutTest.php
- Tests/Form/TypeTestCase.php
- Twig/MenuExtension.php
Just some code improvements based on my IDE code inspect.
Just for suggestion, you should add [scrutinizer](scrutinizer-ci.com), [codeclimate](codeclimate.com) and [sensio insight](insight.sensiolabs.com) tools on your project.
This will help you and contributor to keep code quality.
[Coveralls](coveralls.io) could be a good tools too for test coverage.
Regards.
> Code improve

- Form/Extension/WidgetFormTypeExtension.php
- Resources/doc/3-form-extension-templates.md
- Resources/views/Form/fields.html.twig
Like documented [here](http://getbootstrap.com/components/#input-groups-buttons).
> Add button addons for input groups

- Form/Extension/WidgetCollectionFormTypeExtension.php
- Resources/views/Form/fields.html.twig
| Q             | A
| ------------- | ---
| Replaces | #907
| Sandbox PR | phiamo/MopaBootstrapSandboxBundle#42
> Add option to enable collection child horizontal wrapping

- Menu/Factory/MenuDecorator.php
to solve problem https://github.com/phiamo/MopaBootstrapBundle/issues/1058
> menu: append classes instead of overwriting them when using 'dropdown' option

- Tests/Form/TypeTestCase.php
> Added missing parameters

- Command/BaseBootstrapSymlinkCommand.php
@phiamo requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/phiamo/MopaBootstrapBundle/
> Scrutinizer Auto-Fixes

- Twig/IconExtension.php
- Twig/InitializrTwigExtension.php
> Update Twig extensions to not use initRuntime

- DependencyInjection/MopaBootstrapExtension.php
- Form/Extension/DateTypeExtension.php
- Form/Extension/DatetimeTypeExtension.php
- Form/Extension/EmbedFormExtension.php
- Form/Extension/ErrorTypeFormTypeExtension.php
- Form/Extension/HelpFormTypeExtension.php
- Form/Extension/HorizontalFormTypeExtension.php
- Form/Extension/IconButtonExtension.php
- Form/Extension/LegendFormTypeExtension.php
- Form/Extension/OffsetButtonExtension.php
- Form/Extension/StaticTextExtension.php
- Form/Extension/TabbedFormTypeExtension.php
- Form/Extension/TimeTypeExtension.php
- Form/Extension/WidgetCollectionFormTypeExtension.php
- Form/Extension/WidgetFormTypeExtension.php
- Form/Type/FormActionsType.php
- Form/Type/TabType.php
- Form/Type/TabsType.php
- Resources/config/form.xml
See https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form
> Fix deprecated stuff form FormType and FormTypeExtension

- Resources/views/Form/fields.html.twig
Just the same what symfony did with https://github.com/symfony/symfony/pull/13814
> Make fields.html.twig traitable

- Resources/doc/misc/configuration-reference.md
> Fix intention

- Menu/Factory/MenuDecorator.php
- Resources/doc/extensions/2-navbars.md
- Resources/views/Menu/menu.html.twig
Fix Issue #1169 .
@isometriks will you please assist me in figuring out what else needs to be done here so this can be merged?
> [WIP] Add badges to Menus

- Form/Extension/HorizontalFormTypeExtension.php
- Form/Extension/WidgetCollectionFormTypeExtension.php
- Resources/views/Form/fields.html.twig
- Tests/Form/AbstractDivLayoutTest.php
- Tests/Form/CollectionLayoutTest.php
- Tests/Form/LegendLayoutTest.php
- Tests/Form/SimpleDivLayoutTest.php
Since the prototype gets assigned the parent this should work now I think since it should inherit the horizontal property when building the view.
> Bubble horizontal down like translation_domain does

- Resources/doc/extensions/2-navbars.md
- Resources/views/Navbar/navbar.html.twig
This fixes Issue #1174.
Thank you @isometriks .
> Fix Bottom Navbar & Top and Bottom Navbar On Same Page 

- Command/BaseBootstrapSymlinkCommand.php
PR according to phiamo/MopaBootstrapBundle#1079
> Changed symlink handling on deletion for Windows

- Resources/views/Menu/menu.html.twig
> Use KnpMenuBundle template, not custom label block

- Tests/Form/TypeTestCase.php
> Added horizontal_label_div_class to test

- Resources/views/Form/fields.html.twig
Fix https://github.com/phiamo/MopaBootstrapBundle/pull/1206
> Fix expanded widget inline-btn to use buttons when widget type set.

- composer.json
I _think_ this will allow Twig2, but am not sure if it should be ^2.0 or ~2.0 (or something else)
> Allow twig2

- Resources/views/Form/fields.html.twig
Use `same as` intead of deprecated `sameas` twig test.
> Update deprecated sameas twig test

- Twig/FormExtension.php
- Twig/InitializrTwigExtension.php
It's now provided by Symfony twig bridge
> Remove form_help twig functions
