phiamo/MopaBootstrapBundle

- Resources/views/Form/fields.html.twig
File input should not have a "form-control" class (see http://getbootstrap.com/css/#forms-example). This PR fixes it.
> Do no apply form control class on file input

- Resources/views/Form/fields.html.twig
Currently the default output is : 
```
<div class="collection-item">
<div class="form-group">...</div>
<div class="col-sm-3 col-sm-offset-3">
<a class="btn btn-default" ...>Remove</a>
</div>
</div>
```
However, the ``remove button`` wrapper should be in a ``form-group`` div as well (see http://getbootstrap.com/css/#forms-horizontal) : 
```
<div class="collection-item">
<div class="form-group">...</div>
<div class="form-group">
<div class="col-sm-3 col-sm-offset-3">
<a class="btn btn-default" ...>Remove</a>
</div>
</div>
</div>
```
This PR fixes it.
> Update form_widget_remove_btn block

- Resources/doc/index.md
- Resources/doc/testing-forms.md
- Tests/Form/TypeTestCase.php
Hey. I prepared a `TypeTestCase` class with support of a MopaBootstrapBundle form extensions. It will allow users to write a unit tests for a forms which uses MopaBootstrap form types.
> TypeTestCase

- Resources/views/Form/fields.html.twig
right now, when creating a popover with html, the html is escaped (see http://bootstrap.mohrenweiserpartner.de/mopa/bootstrap/forms/help_texts).
> add data-html to popover toggle

- .travis.yml
- README.md
- Tests/Form/AbstractDivLayoutTest.php
- Tests/Form/SimpleDivLayoutTest.php
- composer.json
This works similarly to how Symfony is doing it. It will render the form element and then use XPath to make sure it is rendered correctly. I made an abstract base class so each extension can be overridden to test to make sure the options work.
> Start adding tests. 

- Resources/doc/2-base-templates.md
- Resources/public/sass/mopabootstrapbundle-3.2.scss
- Resources/views/base_sass_3.2.html.twig
@phiamo We could just do something simple like this for now for people using 3.2+ and then we can switch to the new way in the other branch. What do you think?
> Give a way for SASS 3.2 to use base templates correctly.

- Resources/views/Form/fields.html.twig
added compatibility with feature #12050 [Form] Added "label_format" option (webmozart)
https://github.com/symfony/symfony/commit/832c78f47df9ecef08171ec375c712d5b064427a
> added compatibility with label_format

- Resources/public/sass/mopabootstrapbundle.scss
allow changing `$icon-font-path` within `bootstrap_and_overrides`
> make $icon-font-path able to override

- Resources/doc/assetic-configuration.md
Less wasn't uptodate.
Sass changed with https://github.com/phiamo/MopaBootstrapBundle/pull/1018
> Updated @icon-font-path

- Resources/views/flash.html.twig
According to the official bootlint rule, dismissable alerts must have `alert-dismissible` css class and not `alert-dismissable`.
Related error: https://github.com/twbs/bootlint/wiki/E033
Thanks.
> Use alert-dismissible class

- Form/Extension/DateTypeExtension.php
- Form/Extension/DatetimeTypeExtension.php
- Form/Extension/TimeTypeExtension.php
- Resources/doc/3.3-form-components.md
- Resources/views/Form/fields.html.twig
allow to add reset button to date,time,datetime fields
We've discussed this in https://github.com/phiamo/MopaBootstrapBundle/pull/993 but didn't come into conclusion.
Any widget_Addons cannot be used, because the original code, for example for datetimepicker is:
```
<div data-provider="datetimepicker" class="input-group date" data-date="{% if value %}{{ value|date('Y-m-d H:i') }}{% endif %}" data-link-field="{{ id }}" data-link-format="yyyy-mm-dd hh:ii">
{{ block('form_widget_simple') }}
<input type="hidden" value="{% if value %}{{ value|date('Y-m-d H:i') }}{% endif %}" {{ block('widget_attributes') }}>
<span class="input-group-addon">{{ mopa_bootstrap_icon(widget_addon_icon) }}</span>
</div>
```
And here is no place to put any widget addons.
> Reset date icon

- Resources/public/components/smalot-bootstrap-datetimepicker/js/bootstrap-datetimepicker.js
if default icons are fontawesome - make datetimepicker doesn't break and use fontawesome icons to find component and componentReset (by default it is only looking for glyphicon icons)
> datetimepicker js component and componentReset fix

- Form/Extension/WidgetFormTypeExtension.php
This PR fixes deprecated notices since SF 2.7.
Symfony 2.3+ BC kept.
> Fix deprecated usage of setAllowedValues

- Form/Extension/EmbedFormExtension.php
- Resources/config/form.xml
- Resources/views/Form/fields.html.twig
Adds the ability for displaying 'inline' sub-forms as discussed in https://github.com/phiamo/MopaBootstrapBundle/issues/862
From:
http://symfony.com/doc/current/book/forms.html#embedding-a-single-object
Usage example:
```
$builder->add('parentForm1', 'text', array(
'mapped' => false,
));
$builder->add('parentForm2', 'text', array(
'mapped' => false,
));
$builder->add('settings', new SettingsFormType(), array(
'embed_form' => true,
));
$builder->add('parentForm3', 'text', array(
'mapped' => false,
));
$builder->add('parentForm4', 'text', array(
'mapped' => false,
));
```
> Extension for displaying 'inline' sub-forms.

- Form/Extension/WidgetCollectionFormTypeExtension.php
Fix deprecated `setAllowedTypes` method parameters from SF 2.6.
Symfony 2.3+ BC kept.
> Fix deprecated setAllowedTypes method

- Resources/views/Form/fields.html.twig
There are problems related to label_attr if field.html.twig, it also existing in your demo site: ![demo-site](http://f5.s.qip.ru/BtVUonic.png)
Also, `form_errors(from)` are rendering errors and not returning them.
> Fixing label_attr for widget_type inline-btn and fixing form_errors

- Resources/views/Form/fields.html.twig
The datetime picker was submitting the human readable, display date/time string, rather than the machine readable one.  This was because both the hidden and the display inputs for the field had the same name & id.
I've also made each of the date, datetime and time widgets use similar code for convenience.
> Fix datetime picker

- Resources/doc/3.3-form-components.md
- Resources/views/Form/fields.html.twig
I have a datetimepicker input field (using smalot-bootstrap-datetimepicker) which I'd like to customize. One of them should have the parameter `startView` set to `hour`.
Your example code to initialize the datetimepicker relies on `data-provider="datetimepicker"`. As all of the datetimepickers will have this provider, I cannot target a specific one. What I'd like to do is setting
```
->add('startTime', 'datetime', array(
'datetimepicker' => true,
'attr' => array('data-start-view' => 'hour'),
))
```
Currently this is not possible. As I can see from the form template which renders the different datetimepicker form elements, there is no way to customize the surrounding div. The widget attributes are only applied to the hidden element.
```
<div data-provider="datetimepicker" …
```
> Customize datetimepicker, timepicker and datepicker

- Resources/views/base_initializr.html.twig
and in the `base.html.twig` it's `head_script` too, not `head_scripts`
> keep the same naming style

- Form/Extension/DateTypeExtension.php
- Form/Extension/DatetimeTypeExtension.php
- Form/Extension/TimeTypeExtension.php
Per Symfony: "The Symfony\Component\OptionsResolver\OptionsResolver::setOptional method is deprecated since version 2.6 and will be removed in 3.0. Use the setDefined() method instead."
> Replace deprecated setOptional with setDefined

- Form/Extension/DateTypeExtension.php
- Form/Extension/DatetimeTypeExtension.php
- Form/Extension/TimeTypeExtension.php
This is a fix of #1074 made by @sgilberg.
`version_compare` on kernel **must not** be used as possible because kernel dependency version could be different of framework-bundle.
`method_exists` is more reliable.
Regards
> Use method_exists on resolver instead of version_compare

- Form/Extension/StaticTextExtension.php
Came across an error when using symfony 2.8, this fixes the issue.
```
The extended type specified for the service "mopa_bootstrap.form.type_extension.static_text" does not match the actual extended type. Expected "form", given "text".
```
> fix static_text symfony 2.8

- .travis.yml
File `phpunit.xml.dist` is loaded by default, if `phpunit.xml` is not present.
> travis: drop phpunit default configuration

- Resources/doc/misc/configuration-reference.md
to get rid of the 'cannot contain an empty value' error
> set initial author_url

- Resources/public/less/font-awesome4/variables.less
Fixing fontawesome4 font path in [#934](https://github.com/phiamo/MopaBootstrapBundle/pull/934/files#diff-772526fd3f5419b7924fdfd048754f8eR4) is broken by [#973](https://github.com/phiamo/MopaBootstrapBundle/pull/973/files#diff-772526fd3f5419b7924fdfd048754f8eR4). This PR fixes this degradation.
Thanks.
> Fix degradation of fontawesome4 font path

- Resources/views/Form/fields.html.twig
One sameas was missed in a previous PR.
> twig deprecation - tiny correction for fields.html.twig

- Twig/InitializrTwigExtension.php
InitializrTwigExtension should implement Twig_Extension_GlobalsInterface to suppress the deprecation warning.
> InitializrTwigExtension deprecation warning suppressed

- Resources/views/Form/fields.html.twig
Hi,
I encountered a problem with the money_widget where you remove `{{ widget }}` from the `money_pattern`. 
The problem is, that if you specify a currency in your form field, the `money_pattern` looks as follows: `{{ widget }} <currency>` (e.g. `{{ widget }} <currency>`). Also have a look at the Symfony implementation: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/MoneyType.php#L72-L112
This again leads to missing translation errors even if you specify a translation for your currency but forget to add the leading space.
The solution is to trim the money_widget after manipulating it.
> Trim money_pattern to prevent leading spaces in translation keys

- Resources/views/Form/fields.html.twig
@isometriks @all
I recently experiencend problems on natively disabling inline buttons via symfony2/3 forms.
Does anybody see a big problem in this, or shall we do a minor version bump and tracking in Changelog?
display due to bootstrap is the same, just css / js selectors might have to change.
> make inline buttons abled to be disabled

- Resources/views/Form/fields.html.twig
Adopts the symfony [mechanism](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L246) to disable the translation of form labels.
> Allow disabling label translation

- Resources/views/Form/fields.html.twig
This PR adds support of the sf2.7 option `choice_translation_domain` (see http://symfony.com/blog/new-in-symfony-2-7-form-and-validator-updates#added-choice-translation-domain-domain-to-avoid-translating-options).
For older sf version, there is a fallback to the old `translation_domain`.
> Use choice_translation_domain option

- DependencyInjection/Configuration.php
- Form/Extension/LayoutFormTypeExtension.php
- Resources/config/form.xml
- Resources/doc/misc/configuration-reference.md
- Resources/views/Form/fields.html.twig
- Tests/Form/AbstractDivLayoutTest.php
- Tests/Form/CollectionLayoutTest.php
- Tests/Form/SimpleDivLayoutTest.php
- Tests/Form/TypeTestCase.php
Currently if you don't want an horizontal form, you have to set `'horizontal' => false`. But afaik, to create an inline form (with the `form-inline` class), you have to do something like : 
```
'horizontal' => false,
'attr' => ['class' => 'form-inline'],
```
Which is not really simple.
This PR add a precise way to choose a `default`, `horizontal` or `inline` layout.
- The bundle `horizontal` configuration option is now replaced with `layout`, which accept `false` (default TWBS layout) or `horizontal` (still default value).
- Same thing with the `horizontal` form option, which also accept the `inline` value.
So, this will give : 
| "layout" value | HTML output |
| --- | --- |
| `false` | `<form ...>` |
| `horizontal` | `<form class="form-horizontal" ...>` |
| `inline` | `<form …
> Replace 'horizontal' option with 'layout'

- Resources/views/Form/fields.html.twig
Avoid missing translation notices when translation_domain is set to false on tabs
> Avoid missing translation notices on tabs when translation_domain is set to false
